requirements.txt
Update gryffin version with proper install
=> Gryffin installation

README.md, docs/source/index.rst, summit/domain.py, summit/strategies/base.py
This PR makes minor changes to the README and docs.
=> Docs update

.github/workflows/ci.yml, poetry.lock, pyproject.toml
The ENTMOOT installation process was recently fixed (see https://github.com/cog-imperial/entmoot/pull/1), so that is incorporated.
Also, Github Actions should work properly now.
=> Fix entmoot installation and Github actions

.readthedocs.yml, poetry.lock, pyproject.toml, summit/strategies/entmoot.py, tests/test_strategies.py
Make entmoot an optional dependency and only import if gurobi is available.
=> ENTMOOT optional install

summit/strategies/tsemo.py
Fixes #91 by adding some more detail to the docstring for TSEMO.
=> Update TSEMO docs

summit/strategies/base.py, summit/strategies/factorial_doe.py, summit/strategies/random.py, tests/test_strategies.py
This PR fixes a bug with FullFactorial which caused domains with categorical variables to break.
=> Fix FullFactorial

.github/workflows/ci.yml, summit/__init__.py, summit/benchmarks/experimental_emulator.py, summit/strategies/base.py, summit/strategies/tsemo.py, tests/test_runner.py
The `categorical_method` had a default of "one-hot" instead of None.  
Changed TSEMO to ensure that it gets enough initial data to train a good model.
=> Fix issue with transform that caused problems with SOBO

summit/utils/dataset.py, tests/test_utils.py
This fixes #106 by allowing a `DataSet` to be created using a dictionary.
=> Dict datasets

docs/source/index.rst, docs/source/runner.rst, summit/run.py
This fixes #107 by adding docs for the Runner.
=> Add runner docs

.github/workflows/ci.yml, get_version.py, poetry.lock, pyproject.toml
=> Denali Release (0.8.0)

.github/workflows/ci.yml, summit/__init__.py, summit/strategies/multitask.py, tests/test_strategies.py
This fixes #124 by ensuring that the STBO and MTBO strategies will work with transforms properly.
=> Ensure STBO and MTBO use output instead of data

summit/strategies/base.py, summit/strategies/tsemo.py
Fixing a bug introduced in the categorical transform PR (#132).
=> Fix transform

poetry.lock, pyproject.toml, summit/benchmarks/data/baumgartner_aniline_cn_crosscoupling.csv, summit/benchmarks/data/reizman_suzuki_case_1.csv, summit/benchmarks/data/reizman_suzuki_case_2.csv, summit/benchmarks/data/reizman_suzuki_case_3.csv, summit/benchmarks/data/reizman_suzuki_case_4.csv, summit/benchmarks/experimental_emulator.py, summit/benchmarks/models/baumgartner_aniline_cn_crosscoupling/baumgartner_aniline_cn_crosscoupling.json, summit/benchmarks/models/baumgartner_aniline_cn_crosscoupling_descriptors/baumgartner_aniline_cn_crosscoupling_descriptors.json, summit/benchmarks/models/reizman_suzuki_case_1/reizman_suzuki_case_1.json, summit/benchmarks/models/reizman_suzuki_case_2/reizman_suzuki_case_2.json, summit/benchmarks/models/reizman_suzuki_case_3/reizman_suzuki_case_3.json, summit/benchmarks/models/reizman_suzuki_case_4/reizman_suzuki_case_4.json, summit/domain.py, summit/strategies/entmoot.py, summit/strategies/multitask.py, summit/strategies/neldermead.py, summit/strategies/snobfit.py, summit/strategies/sobo.py, tests/test_benchmarks.py, tests/test_domain.py
fixes #117 by adding a condition to variable name check.
=> Prevent naming variables keywords

summit/benchmarks/snar.py
Fixes #141 by correcting reservoir concentrations and volumes to match the paper.
=> Fix initial snar concentrations and volume

summit/strategies/tsemo.py
Allows the number of spectral points to be passed into the rff approximations within the fit function.
=> Update tsemo.py, Line 213, Added n_spectral_points=self.n_spectral_points

summit/strategies/multitask.py
Changed all instances of 'float' to 'double' in the multitask strategy as per the suggestion here: https://github.com/pytorch/botorch/issues/1055
=> change all mtbo float to double

summit/benchmarks/experimental_emulator.py
This PR fixes https://github.com/sustainable-processes/summit/issues/184, which was caused by an update to sklearn.
=> Remove _check_param_grid

summit/benchmarks/snar.py, summit/tests/test_benchmarks.py
Fix #185 by updating the kinetic equations to properly represent the original paper [here](https://pubs.rsc.org/en/content/articlelanding/2017/RE/C6RE00109B)
=> Update kinetic parameters

summit/strategies/sobo.py
This PR fixes https://github.com/sustainable-processes/summit/issues/160 by correcting the categorical method keyword in sobo.
=> Fix SOBO issue

docs/source/experiments_benchmarks/index.rst, docs/source/installation.rst, docs/source/tutorials/intro.ipynb, docs/source/tutorials/new_benchmarks.ipynb, summit/strategies/random.py, summit/strategies/sobo.py, summit/strategies/tsemo.py
I am going through the docs, so maybe I will add more commits here, no hurry to merge this PR.
=> Small edits in the docs

summit/domain.py, summit/experiment.py, summit/strategies/base.py, summit/strategies/factorial_doe.py, summit/strategies/multitask.py, summit/strategies/neldermead.py, summit/strategies/snobfit.py, summit/strategies/tsemo.py, summit/tests/test_strategies.py
=> Improve TSEMO categorical

summit/run.py
This fixes #225 by not saving unless asked to.
=> Fix runner saving

summit/benchmarks/snar.py
=> Change SnAr limits

.github/workflows/ci.yml
Update to v8 of Gr1N/setup-poetry
=> Update poetry version of publish workflow

summit/strategies/base.py
Update the domain in the transform to use the transform domain instead of the original domain
=> Update transform domain

summit/strategies/base.py
Simplify and improve descriptors merge in transform
=> Change descriptors merge code
